export const GET_LIST_NOTES = 'GET_LIST_NOTES'
export const CREATE_ARRAY_NOTE = 'CREATE_ARRAY_NOTE'
export const DEL_ALL_NOTES = 'DEL_ALL_NOTES'
export const DEL_ITEM_NOTE = 'DEL_ITEM_NOTE'
export const SAVE_NOTE = 'SAVE_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const SAVE_EDIT_NOTE = 'SAVE_EDIT_NOTE'
export const NOTE_DETAILS = 'NOTE_DETAILS'

export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE'
export const UPDATE_AREA_VALUE = 'UPDATE_AREA_VALUE'

export const UPDATE_AUTHOR_VALUE = 'UPDATE_AUTHOR_VALUE'
export const UPDATE_COMMENT_VALUE = 'UPDATE_COMMENT_VALUE'
export const SAVE_COMENT = 'SAVE_COMENT'

export const MESSAGE_STATUS = 'MESSAGE_STATUS'
